{% set version = "0.7.0" %}

package:
  name: libgpuarray
  version: {{ version }}

source:
  fn: libgpuarray-{{ version }}.tar.gz
  url: https://github.com/Theano/libgpuarray/archive/v{{ version }}.tar.gz

build:
  number: 0
  skip: true  # [win and py35]
  skip: true  # [not win and not py27]
  features:
    - vc9     # [win and py27]
    - vc10    # [win and py34]
    - vc14    # [win and (py35 or py36)]

requirements:
  build:
    - m2-git         [win]
    - m2-filesystem  [win]
    - git            [not win]
    - {{ compiler('c') }}
    - cmake
    - mako
    - python  # version doesn't matter here
  run:
    - vs2008_runtime  [win and py27]
    - vs2010_runtime  [win and py34]
    - vs2015_runtime  [win and (py35 or py36)]

about:
  home: http://github.com/Theano/libgpuarray
  license: ISC
  license_file: LICENSE
  summary: 'Library to manipulate arrays on GPU'
  doc_url: http://deeplearning.net/software/libgpuarray/
  dev_url: http://github.com/Theano/libgpuarray
