version: '1.0.{build}'  # This number doesn't matter

pull_requests:
  do_not_increment_build_number: true

platform:
  - x64

image: Visual Studio 2015

clone_folder: C:\projects\libgpuarray

configuration:
  - Release

environment:
  BINSTAR_TOKEN:
    secure: pPGGv/pzNILDCClm4VNOv9lJ9Bah+iuJ22j4oLCaHzM8eNre8bfALOhMRIERhd55
    #secure: jK8icdT9ukloE7xSj7fqiCmtM/aTNLTUEeD2HLRP5+9GI5oGkK4jt/uYEcKDtfwO

  matrix:
    - CONDA_LOC: "C:\\Miniconda-x64"
    - CONDA_LOC: "C:\\Miniconda35-x64"

install:
  # This breaks conda-build because of git
  - cmd: rmdir C:\cygwin /s /q
  - cmd: call %CONDA_LOC%\Scripts\activate.bat
  - cmd: set PYTHONUNBUFFERED=1
  - cmd: conda install -n root --yes conda conda-env conda-build anaconda-client
  # We borrow a trick from conda-forge to fix the VS2008 compiler
  - cmd: conda config --append channels conda-forge
  - cmd: conda install --yes vs2008_express_vc_python_patch
  - cmd: call setup_x64

build: off

test_script:
  - cmd: for /f "tokens=*" %%i in ('python -c "import versioneer; print(versioneer.get_version())"') do set GPUARRAY_VERSION=%%i
  - cmd: echo %GPUARRAY_VERSION%
  - cmd: conda build conda
  - ps: |
      if($env:appveyor_repo_tag -eq 'False') {
        anaconda upload --user=abergeron "%CONDA_LOC%"\conda-bld\win-64\pygpu*
        anaconda upload --user=abergeron "%CONDA_LOC%"\conda-bld\win-64\libgpuarray*
      }
