version: '0.7.0.{build}'

pull_requests:
  do_not_increment_build_number: true

init:
  - git config --global core.autocrlf input
  - cmd: cmake --version
  - cmd: msbuild /version

platform:
  - x64

clone_folder: C:\projects\libgpuarray

configuration:
  - Release

environment:
  matrix:
    - CONDA_LOC: "C:\\Miniconda-x64"

install:
  # This breaks conda-build because of git
  - cmd: rmdir C:\cygwin /s /q
  - cmd: call %CONDA_LOC%\Scripts\activate.bat
  - cmd: set PYTHONUNBUFFERED=1
  - cmd: conda install -n root --yes conda conda-env conda-build anaconda-client

build: script

build_script:
  - conda build conda

#deploy_script:
