version: '1.0.{build}'  # This number doesn't matter

pull_requests:
  do_not_increment_build_number: true

platform:
  - x64

image: Visual Studio 2015

clone_folder: C:\projects\libgpuarray

configuration:
  - Release

environment:
  matrix:
    - CONDA_LOC: "C:\\Miniconda-x64"
      VS_PATH: "C:\\Users\\appveyor\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0"
    - CONDA_LOC: "C:\\Miniconda35-x64"
      VS_PATH: "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC"

install:
  # This breaks conda-build because of git
  - cmd: rmdir C:\cygwin /s /q
  - cmd: call %CONDA_LOC%\Scripts\activate.bat
  - cmd: set PYTHONUNBUFFERED=1
  - cmd: conda install -n root --yes conda conda-env conda-build anaconda-client

build: off

test_script:
  - cmd: for /f "tokens=*" %%i in ('python -c "import versioneer; print(versioneer.get_version())"') do set GPUARRAY_VERSION=%%i
  - cmd: "%VS_PATH%"\vcvarsall x64
  - cmd: conda build conda

deploy_script:
  - cmd: .ci-support/upload.bat
