{% set version = "0.7.0" %}

package:
  name: pygpu
  version: {{ version }}

source:
  fn: libgpuarray-{{ version }}.tar.gz
  url: https://github.com/Theano/libgpuarray/archive/v{{ version }}.tar.gz

build:
  number: 0
  detect_binary_files_with_prefix: False

requirements:
  build:
    - m2-git         [win]
    - m2-filesystem  [win]
    - git            [not win]
    - python {{ python }}
    - cython >=0.25
    - numpy {{ numpy }}
    - mako
    - setuptools
    - libgpuarray =={{ version }}

  run:
    - python {{ python }}
    - {{ pin_compatible('numpy') }}
    - mako
    - six
    - libgpuarray =={{ version }}

about:
  home: http://github.com/Theano/libgpuarray
  license: ISC
  license_file: LICENSE
  summary: 'Library to manipulate arrays on GPU'
  doc_url: http://deeplearning.net/software/libgpuarray/
  dev_url: http://github.com/Theano/libgpuarray
